class Chip::Models::ClientDetail
	attr_accessor :email
	attr_accessor :phone
	attr_accessor :full_name
	attr_accessor :personal_code
	attr_accessor :street_address
	attr_accessor :country
	attr_accessor :city
	attr_accessor :zip_code
	attr_accessor :shipping_street_address
	attr_accessor :shipping_country
	attr_accessor :shipping_city
	attr_accessor :shipping_zip_code
	attr_accessor :cc
	attr_accessor :bcc
	attr_accessor :legal_name
	attr_accessor :brand_name
	attr_accessor :registration_number
	attr_accessor :tax_number
end