class Chip::Models::Purchase
	attr_accessor :uuid
	attr_accessor :order_id
	attr_accessor :client
	attr_accessor :purchase
	attr_accessor :payment
	attr_accessor :issuer_details
	attr_accessor :transaction_data
	attr_accessor :status
	attr_accessor :status_history
	attr_accessor :viewed_on
	attr_accessor :company_id
	attr_accessor :is_testean
	attr_accessor :user_id
	attr_accessor :brand_id
	attr_accessor :billing_template_id
	attr_accessor :client_id
	attr_accessor :send_receiptean
	attr_accessor :is_recurring_tokenean
	attr_accessor :recurring_token
	attr_accessor :skip_captureean
	attr_accessor :reference_generated
	attr_accessor :reference
	attr_accessor :issued
	attr_accessor :due
	attr_accessor :refund_availability
	attr_accessor :refundable_amount
	attr_accessor :currency_conversion
	attr_accessor :payment_methods_whitelist
	attr_accessor :success_redirect
	attr_accessor :failure_redirect
	attr_accessor :cancel_redirect
	attr_accessor :success_callback
	attr_accessor :creator_agent
	attr_accessor :platform
	attr_accessor :product
	attr_accessor :created_from_ip
	attr_accessor :invoice_url
	attr_accessor :checkout_url
	attr_accessor :direct_post_url
end
